# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("jderobot")

# Modules:
import ardroneextra_ice
import body_ice
import bodyencoders_ice
import bodymotors_ice
import bodymovements_ice
import camera_ice
import cmdvel_ice
import common_ice
import containers_ice
import datetime_ice
import emSensor_ice
import encoders_ice
import exceptions_ice
import genericData_ice
import image_ice
import jcm_ice
import kinectleds_ice
import laser_ice
import motors_ice
import namingService_ice
import naofollowball_ice
import naomotions_ice
import navdata_ice
import pointcloud_ice
import pose3d_ice
import pose3dencoders_ice
import pose3dmotors_ice
import primitives_ice
import ptencoders_ice
import ptmotors_ice
import recorder_ice
import remoteCloud_ice
import remoteConfig_ice
import replayControl_ice
import sonars_ice
import varcolor_ice
import visualization_ice
import wiimote_ice

# Submodules:
